# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chartwise.llm.v1 import gateway_pb2 as chartwise_dot_llm_dot_v1_dot_gateway__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chartwise/llm/v1/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LlmGatewayStub:
    """LlmGateway is the only path from Chartwise services to an LLM provider.
    It owns rate limiting, retries and circuit breaking so callers don't have to.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/chartwise.llm.v1.LlmGateway/Complete',
                request_serializer=chartwise_dot_llm_dot_v1_dot_gateway__pb2.CompleteRequest.SerializeToString,
                response_deserializer=chartwise_dot_llm_dot_v1_dot_gateway__pb2.CompleteResponse.FromString,
                _registered_method=True)


class LlmGatewayServicer:
    """LlmGateway is the only path from Chartwise services to an LLM provider.
    It owns rate limiting, retries and circuit breaking so callers don't have to.
    """

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=chartwise_dot_llm_dot_v1_dot_gateway__pb2.CompleteRequest.FromString,
                    response_serializer=chartwise_dot_llm_dot_v1_dot_gateway__pb2.CompleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chartwise.llm.v1.LlmGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chartwise.llm.v1.LlmGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmGateway:
    """LlmGateway is the only path from Chartwise services to an LLM provider.
    It owns rate limiting, retries and circuit breaking so callers don't have to.
    """

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chartwise.llm.v1.LlmGateway/Complete',
            chartwise_dot_llm_dot_v1_dot_gateway__pb2.CompleteRequest.SerializeToString,
            chartwise_dot_llm_dot_v1_dot_gateway__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
